### ISSUE TITLE
Tweet is not re-tweeted if hashtag is occured at the beginning of the tweet

### ISSUE THREAD

**Issue by realslimshanky** [amandeepmittal/100DaysOfCode#1]
Tweet in form of "#100DaysOfCode ......" is not retweeted
example, https://twitter.com/realslimshanky/status/816352899257102336

**Comment by amandeepmittal** [comment]
It does, however the it is a random process. Not every tweet with hashtag "#100DaysOfCode" gets retweeted by the bot. Check the bot account: [@_100DaysOfCode](https://twitter.com/_100DaysOfCode)

**Comment by realslimshanky** [comment]
Sorry for the worry, that cleared my doubt, thanks :)
